apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    storetype: nfs
spec:
  storageClassName: normal-pv
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfsfileshare
    server: 172.17.8.101